version: 2

jobs:
  build:
    docker:
      - image: docker.io/redjays/c7:docker-ce
    working_directory: /project
    environment:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build dind
          command: bash -x build.sh
      - run:
          name: push dind
          command: bash -x publish.sh
